name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      path:
        description: "Path to link"
        required: true
        default: "./oo-lib-py/"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repository
        uses: actions/checkout@v5
        
      - name: make sure 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install pytest
        working-directory: oo-lib-py/
        run: pip install pytest
        
      - name: run the python app
        working-directory: oo-lib-py/
        run: python3 -m app

      - name: run our python tests
        working-directory: oo-lib-py/
        run: python3 -m pytest
